name: shoufeng_order
description: shoufeng ordering system

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  fancy_bottom_navigation: ^0.3.2
  wave: ^0.0.8
  avatar_glow: ^1.1.0
  fl_chart: ^0.5.1
  slide_popup_dialog: ^0.0.2
  firebase_core: ^0.4.3+1
  cloud_firestore: ^0.13.0+1
  firebase_storage: ^3.1.1
  loading_animations: ^2.1.0
  bouncing_widget: ^1.2.0
  easy_dialog: ^1.0.5
  shared_preferences: ^0.5.6
  animated_text_kit: ^2.0.0
  beauty_textfield: ^0.0.1
  progress_indicator_button: ^0.0.3
  bot_toast: ^2.2.1
  flutter_spinkit: ^4.1.1+1
  flutter_staggered_grid_view: ^0.3.0




dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  assets:
    - images/


  fonts:
    - family: Courgette
      fonts:
        - asset: fonts/Courgette-Regular.ttf
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
    - family: Yuanti
      fonts:
        - asset: fonts/Yuanti.ttc
    - family: Heiti
      fonts:
        - asset: fonts/STHeiti-Medium.ttc
    - family: KaushanScript
      fonts:
        - asset: fonts/KaushanScript-Regular.ttf
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf
    - family: LilitaOne
      fonts:
        - asset: fonts/LilitaOne-Regular.ttf


  uses-material-design: true

